language: java
sudo: false
cache:
  directories:
  - $HOME/.m2
jdk:
- openjdk6
#install: mvn install -DskipTests=true -q

# Run build and push build to https://scan.coverity.com/
addons:
  coverity_scan:
    project:
      name: "tracee/tracee"
      description: "Build submitted via Travis CI"
    notification_email: sven.bunge@nnga.de
    build_command_prepend: "mvn clean"
    build_command:   "mvn install -DskipTests=true -q"
    branch_pattern: coverity_scan

# Run unit and integration tests
script: mvn verify -B -q

after_success: ! '[[ $TRAVIS_BRANCH == "master" && $TRAVIS_REPO_SLUG == "tracee/tracee"
  && $TRAVIS_PULL_REQUEST == "false" ]] && { curl https://raw.githubusercontent.com/holisticon/travis-configuration/master/settings.xml --location
  --create-dirs -o target/travis/settings.xml; } && { mvn cobertura:cobertura coveralls:report deploy -q --settings target/travis/settings.xml
  -Dgpg.skip=true; }'

notifications:
  webhooks:
    urls:
      - $GITTER_WEBHOOK
    on_success: change
    on_failure: always
    on_start: false
